### ISSUE TITLE
Gib Acesss

### ISSUE THREAD

**Issue by PAUL-OP** [dusklight00/fft-image-canvas-generator#1]
Just want to check it out

**Comment by dusklight00** [comment]
@PAUL-OP You can clone the repo if you want to do any changes you can send the pull request, I'll merge it.

**Comment by PAUL-OP** [comment]
Ok! So what's the uhh use of this? Like what is the project based on?

**Comment by dusklight00** [comment]
@PAUL-OP Basically it is a module that will be used in another project. To create those music album videos automatically.
